version: '3'
services:
  springboot:
    build:
      context: ./Ambulance_Spring
      dockerfile: Dockerfile
    container_name: springboot_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ambulance_db:3306/portf
      SPRING_DATASOURCE_USERNAME: ussr
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8080:8080"
    networks:
      - devops_network
    depends_on:
      - ambulance_db

  ambulance_db:
    container_name: ambulance_db
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: portf
      MYSQL_USER: ussr
      MYSQL_PASSWORD: 123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devops_network
    ports:
      - "3306:3306"

volumes:
  mysql_data:

networks:
  devops_network:
    external: true