version: '3'
services:
  springboot:
    build:
      context: ./Ambulance_Spring
      dockerfile: Dockerfile
    container_name: springboot_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ambulance_db:3306/portf?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "123"
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      ambulance_db:
        condition: service_healthy

  ambulance_db:
    container_name: ambulance_db
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: portf
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
