services:
  springboot:
    build:
      context: ./Ambulance_Spring
      dockerfile: Dockerfile
    container_name: springboot_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db2:3306/portf
      SPRING_DATASOURCE_USERNAME: ussr
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8080:8080"
    networks:
      - dev_network
    depends_on:
      - db2

  db2:
    container_name: ambulance_db
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: portf
      MYSQL_USER: ussr
      MYSQL_PASSWORD: 123
    volumes:
      - vol:/var/lib/mysql
    networks:
      - dev_network
    ports:
      - "3306:3306"

volumes:
  vol:

networks:
  dev_network:
    driver: bridge