services:
  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - net1


  db:
    container_name: db-bilal
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: rescueroute
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - res:/var/lib/mysql
    networks:
      - net1


volumes:
  res:

networks:
  net1: